import mongoose from 'mongoose';
import Quiz from './models/Quiz.js';
import dotenv from 'dotenv';

dotenv.config();

const quizQuestions = [
  // Java Questions (25 questions)
  { subject: 'Java', question: 'Which of the following is not a Java features?', options: ['Dynamic', 'Architecture Neutral', 'Use of pointers', 'Object-oriented'], answer: 'Use of pointers' },
  { subject: 'Java', question: 'What is the extension of java code files?', options: ['.js', '.txt', '.class', '.java'], answer: '.java' },
  { subject: 'Java', question: 'Which environment variable is used to set the java path?', options: ['MAVEN_Path', 'JavaPATH', 'JAVA', 'JAVA_HOME'], answer: 'JAVA_HOME' },
  { subject: 'Java', question: 'Which of the following is not an OOPS concept in Java?', options: ['Polymorphism', 'Inheritance', 'Compilation', 'Encapsulation'], answer: 'Compilation' },
  { subject: 'Java', question: 'What is not the use of "this" keyword in Java?', options: ['Referring to the instance variable when a local variable has the same name', 'Passing itself to the method of the same class', 'Passing itself to another method', 'Calling another constructor in constructor chaining'], answer: 'Passing itself to the method of the same class' },
  { subject: 'Java', question: 'Which of the following is a type of polymorphism in Java Programming?', options: ['Multiple polymorphism', 'Compile time polymorphism', 'Multilevel polymorphism', 'Execution time polymorphism'], answer: 'Compile time polymorphism' },
  { subject: 'Java', question: 'What is Inheritance in Java?', options: ['Inheritance is a mechanism where a new class is derived from an existing class', 'Inheritance is a mechanism where multiple classes are derived from a single class', 'Inheritance is a mechanism where a single class is derived from multiple classes', 'None of the above'], answer: 'Inheritance is a mechanism where a new class is derived from an existing class' },
  { subject: 'Java', question: 'Which of the following is true about inheritance in Java?', options: ['Java supports multiple inheritance', 'Java does not support multiple inheritance', 'Java supports hybrid inheritance', 'Java supports multilevel inheritance only'], answer: 'Java does not support multiple inheritance' },
  { subject: 'Java', question: 'What is the output of the following Java program code snippet?', options: ['Compilation Error', 'Runtime Error', 'Hello World', 'None'], answer: 'Hello World' },
  { subject: 'Java', question: 'Which of the following option leads to the portability and security of Java?', options: ['Bytecode is executed by JVM', 'The applet makes the Java code secure and portable', 'Use of exception handling', 'Dynamic binding between objects'], answer: 'Bytecode is executed by JVM' },
  { subject: 'Java', question: 'Which of the following is not a Java profiler?', options: ['JProfiler', 'Eclipse Profiler', 'JVM', 'JConsole'], answer: 'JVM' },
  { subject: 'Java', question: 'Which of the following creates a List?', options: ['List<String> list = new List<String>();', 'List<String> list = new ArrayList<String>();', 'ArrayList<String> list = new List<String>();', 'None'], answer: 'List<String> list = new ArrayList<String>();' },
  { subject: 'Java', question: 'What is the initial quantity of the ArrayList list?', options: ['5', '0', '10', '100'], answer: '10' },
  { subject: 'Java', question: 'What is the default value of Array for integer datatype?', options: ['null', '0', 'undefined', '1'], answer: '0' },
  { subject: 'Java', question: 'Arrays in Java are-', options: ['Object references', 'objects', 'Primitive data type', 'None'], answer: 'objects' },
  { subject: 'Java', question: 'When is the object created with new keyword?', options: ['At run time', 'At compile time', 'Depends on the code', 'None'], answer: 'At run time' },
  { subject: 'Java', question: 'Identify the corrected definition of a package.', options: ['A package is a collection of editing tools', 'A package is a collection of classes', 'A package is a collection of classes and interfaces', 'A package is a collection of classes and editing tools'], answer: 'A package is a collection of classes and interfaces' },
  { subject: 'Java', question: 'Which of the following is a reserved keyword in Java?', options: ['object', 'strictfp', 'main', 'system'], answer: 'strictfp' },
  { subject: 'Java', question: 'Which of the following is true about the anonymous inner class?', options: ['It has only methods', 'Objects cant be created', 'It has a fixed class name', 'It has no class name'], answer: 'It has no class name' },
  { subject: 'Java', question: 'Which of the following is false about String?', options: ['String is immutable', 'String is a primitive datatype', 'String is a class', 'None'], answer: 'String is a primitive datatype' },
  { subject: 'Java', question: 'What is the output of Math.floor(3.6)?', options: ['3', '4', '3.0', '4.0'], answer: '3.0' },
  { subject: 'Java', question: 'Which method is used to find the length of the string?', options: ['length()', 'size()', 'getSize()', 'getLength()'], answer: 'length()' },
  { subject: 'Java', question: 'Which of these is returned by operators &, |?', options: ['Integer', 'Boolean', 'Character', 'Float'], answer: 'Integer' },
  { subject: 'Java', question: 'What is the range of short data type in Java?', options: ['-128 to 127', '-32768 to 32767', '-2147483648 to 2147483647', 'None'], answer: '-32768 to 32767' },
  { subject: 'Java', question: 'Which of the following is the correct way of implementing an interface?', options: ['class className extends interfaceName', 'class className implements interfaceName', 'class className imports interfaceName', 'None'], answer: 'class className implements interfaceName' },

  // Python Questions (25 questions)
  { subject: 'Python', question: 'What is the correct extension of the Python file?', options: ['.python', '.pl', '.py', '.p'], answer: '.py' },
  { subject: 'Python', question: 'Which of the following is used to define a block of code in Python language?', options: ['Indentation', 'Key', 'Brackets', 'All of the mentioned'], answer: 'Indentation' },
  { subject: 'Python', question: 'Which keyword is used for function in Python language?', options: ['Function', 'def', 'Fun', 'Define'], answer: 'def' },
  { subject: 'Python', question: 'Which of the following character is used to give single-line comments in Python?', options: ['//', '#', '!', '/*'], answer: '#' },
  { subject: 'Python', question: 'What will be the value of the following Python expression? 4 + 3 % 5', options: ['4', '7', '2', '0'], answer: '7' },
  { subject: 'Python', question: 'Which of the following is the correct extension of the Python file?', options: ['.python', '.pl', '.py', '.p'], answer: '.py' },
  { subject: 'Python', question: 'What is the method inside the class in python language?', options: ['Object', 'Function', 'Attribute', 'Argument'], answer: 'Function' },
  { subject: 'Python', question: 'Which of the following is not a core data type in Python programming?', options: ['Tuples', 'Lists', 'Class', 'Dictionary'], answer: 'Class' },
  { subject: 'Python', question: 'What does pip stand for python?', options: ['Pip Installs Python', 'Pip Installs Packages', 'Preferred Installer Program', 'All of the mentioned'], answer: 'Preferred Installer Program' },
  { subject: 'Python', question: 'Which of the following is the use of id() function in python?', options: ['Every object doesnt have a unique id', 'Id returns the identity of the object', 'All of the mentioned', 'None of the mentioned'], answer: 'Id returns the identity of the object' },
  { subject: 'Python', question: 'What is the order of precedence in python?', options: ['Exponential, Parentheses, Multiplication, Division, Addition, Subtraction', 'Parentheses, Exponential, Multiplication, Division, Addition, Subtraction', 'Parentheses, Exponential, Division, Multiplication, Addition, Subtraction', 'Parentheses, Exponential, Division, Multiplication, Subtraction, Addition'], answer: 'Parentheses, Exponential, Multiplication, Division, Addition, Subtraction' },
  { subject: 'Python', question: 'What is the maximum possible length of an identifier in python?', options: ['31 characters', '63 characters', '79 characters', 'None of the mentioned'], answer: 'None of the mentioned' },
  { subject: 'Python', question: 'Which of the following is not a keyword in python language?', options: ['val', 'raise', 'try', 'with'], answer: 'val' },
  { subject: 'Python', question: 'Which of the following functions can help us to find the version of python that we are currently working on?', options: ['sys.version(1)', 'sys.version(0)', 'sys.version()', 'sys.version'], answer: 'sys.version' },
  { subject: 'Python', question: 'Python supports the creation of anonymous functions at runtime, using a construct called', options: ['pi', 'anonymous', 'lambda', 'none of the mentioned'], answer: 'lambda' },
  { subject: 'Python', question: 'What is the order of namespaces in which Python looks for an identifier?', options: ['Python first searches the global namespace, then the local namespace, finally the built-in namespace', 'Python first searches the built-in namespace, then the global namespace, finally the local namespace', 'Python first searches the local namespace, then the global namespace, finally the built-in namespace', 'None of the mentioned'], answer: 'Python first searches the local namespace, then the global namespace, finally the built-in namespace' },
  { subject: 'Python', question: 'Which of the following is the truncation division operator in Python?', options: ['|', '//', '/', '%'], answer: '//' },
  { subject: 'Python', question: 'What will be the output of the following Python code? print(0.1 + 0.2 == 0.3)', options: ['True', 'False', 'Machine dependent', 'Error'], answer: 'False' },
  { subject: 'Python', question: 'Which of the following is a Python tuple?', options: ['[1, 2, 3]', '(1, 2, 3)', '{1, 2, 3}', '{}'], answer: '(1, 2, 3)' },
  { subject: 'Python', question: 'What will be the output of the following Python code? list1 = [1, 2, 3, 4] list1.append([5, 6, 7, 8]) print(len(list1))', options: ['8', '5', '4', '12'], answer: '5' },
  { subject: 'Python', question: 'Which of the following is the correct way to open a file in Python?', options: ['f = open("file.txt")', 'f = file("file.txt")', 'f = File("file.txt")', 'f = openfile("file.txt")'], answer: 'f = open("file.txt")' },
  { subject: 'Python', question: 'Which module in Python supports regular expressions?', options: ['re', 'regex', 'pyregex', 'none of the mentioned'], answer: 're' },
  { subject: 'Python', question: 'What will be the output of the following Python code? x = "abcdef" i = "" for i in x: print(i, end=" ")', options: ['a b c d e f', 'abcdef', 'f', 'error'], answer: 'a b c d e f' },
  { subject: 'Python', question: 'Which of the following is used to create an empty set in Python?', options: ['()', '[]', '{}', 'set()'], answer: 'set()' },
  { subject: 'Python', question: 'What is the output of print(type([]) is list)?', options: ['True', 'False', 'Error', 'None'], answer: 'True' },

  // DSA Questions (25 questions)
  { subject: 'DSA', question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], answer: 'O(log n)' },
  { subject: 'DSA', question: 'Which data structure uses LIFO principle?', options: ['Queue', 'Stack', 'Array', 'Linked List'], answer: 'Stack' },
  { subject: 'DSA', question: 'What is the worst case time complexity of Quick Sort?', options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'], answer: 'O(n²)' },
  { subject: 'DSA', question: 'Which of the following is not a stable sorting algorithm?', options: ['Merge Sort', 'Bubble Sort', 'Quick Sort', 'Insertion Sort'], answer: 'Quick Sort' },
  { subject: 'DSA', question: 'What is the space complexity of merge sort?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(n)' },
  { subject: 'DSA', question: 'In which data structure, elements are added at one end and removed from the other end?', options: ['Stack', 'Queue', 'Array', 'Tree'], answer: 'Queue' },
  { subject: 'DSA', question: 'What is the height of a complete binary tree with n nodes?', options: ['log n', 'n', 'n/2', 'n log n'], answer: 'log n' },
  { subject: 'DSA', question: 'Which traversal of binary tree gives sorted order in BST?', options: ['Preorder', 'Inorder', 'Postorder', 'Level order'], answer: 'Inorder' },
  { subject: 'DSA', question: 'What is the time complexity of inserting an element in a hash table?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(1)' },
  { subject: 'DSA', question: 'Which algorithm is used to find the shortest path in a weighted graph?', options: ['BFS', 'DFS', 'Dijkstra', 'Kruskal'], answer: 'Dijkstra' },
  { subject: 'DSA', question: 'What is the maximum number of nodes at level L in a binary tree?', options: ['2^L', '2^(L-1)', '2^(L+1)', 'L^2'], answer: '2^L' },
  { subject: 'DSA', question: 'Which data structure is used for implementing recursion?', options: ['Queue', 'Stack', 'Array', 'Linked List'], answer: 'Stack' },
  { subject: 'DSA', question: 'What is the time complexity of deleting an element from the middle of an array?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(n)' },
  { subject: 'DSA', question: 'Which sorting algorithm has the best average case time complexity?', options: ['Bubble Sort', 'Selection Sort', 'Merge Sort', 'Insertion Sort'], answer: 'Merge Sort' },
  { subject: 'DSA', question: 'What is a complete binary tree?', options: ['All levels are filled', 'All levels are filled except possibly the last', 'Only left subtree exists', 'Only right subtree exists'], answer: 'All levels are filled except possibly the last' },
  { subject: 'DSA', question: 'Which algorithm is used to detect cycle in an undirected graph?', options: ['BFS', 'DFS', 'Union-Find', 'All of the above'], answer: 'All of the above' },
  { subject: 'DSA', question: 'What is the time complexity of heap sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], answer: 'O(n log n)' },
  { subject: 'DSA', question: 'In a min heap, the parent node is always _____ than its children', options: ['Greater', 'Smaller', 'Equal', 'None'], answer: 'Smaller' },
  { subject: 'DSA', question: 'What is the maximum number of edges in a simple graph with n vertices?', options: ['n', 'n-1', 'n(n-1)/2', 'n²'], answer: 'n(n-1)/2' },
  { subject: 'DSA', question: 'Which data structure is used in breadth-first search?', options: ['Stack', 'Queue', 'Priority Queue', 'Deque'], answer: 'Queue' },
  { subject: 'DSA', question: 'What is the time complexity of finding an element in a balanced BST?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(log n)' },
  { subject: 'DSA', question: 'Which algorithm is used to find minimum spanning tree?', options: ['Dijkstra', 'Floyd-Warshall', 'Kruskal', 'Bellman-Ford'], answer: 'Kruskal' },
  { subject: 'DSA', question: 'What is the space complexity of quicksort in the average case?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(log n)' },
  { subject: 'DSA', question: 'Which data structure allows insertion and deletion at both ends?', options: ['Stack', 'Queue', 'Deque', 'Priority Queue'], answer: 'Deque' },
  { subject: 'DSA', question: 'What is the time complexity of counting sort?', options: ['O(n)', 'O(n + k)', 'O(n log n)', 'O(n²)'], answer: 'O(n + k)' },

  // Add more subjects with 20+ questions each...
  // DBMS Questions (20 questions)
  { subject: 'DBMS', question: 'What does DBMS stand for?', options: ['Database Management System', 'Data Base Management System', 'Database Manipulation System', 'Data Management System'], answer: 'Database Management System' },
  { subject: 'DBMS', question: 'Which of the following is not a type of database?', options: ['Hierarchical', 'Network', 'Relational', 'Decentralized'], answer: 'Decentralized' },
  { subject: 'DBMS', question: 'What is a primary key?', options: ['A key that can be null', 'A key that uniquely identifies a record', 'A key that can have duplicates', 'None of the above'], answer: 'A key that uniquely identifies a record' },
  { subject: 'DBMS', question: 'Which normal form eliminates transitive dependency?', options: ['1NF', '2NF', '3NF', 'BCNF'], answer: '3NF' },
  { subject: 'DBMS', question: 'What is ACID in database?', options: ['Atomicity, Consistency, Isolation, Durability', 'Atomicity, Concurrency, Isolation, Durability', 'Accuracy, Consistency, Isolation, Durability', 'None'], answer: 'Atomicity, Consistency, Isolation, Durability' },
  { subject: 'DBMS', question: 'Which SQL command is used to retrieve data?', options: ['INSERT', 'UPDATE', 'SELECT', 'DELETE'], answer: 'SELECT' },
  { subject: 'DBMS', question: 'What is a foreign key?', options: ['A key from another table', 'A primary key', 'A unique key', 'A composite key'], answer: 'A key from another table' },
  { subject: 'DBMS', question: 'Which join returns all records from both tables?', options: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'FULL OUTER JOIN'], answer: 'FULL OUTER JOIN' },
  { subject: 'DBMS', question: 'What is denormalization?', options: ['Process of reducing redundancy', 'Process of adding redundancy', 'Process of removing data', 'None'], answer: 'Process of adding redundancy' },
  { subject: 'DBMS', question: 'Which of the following is not an aggregate function?', options: ['COUNT', 'SUM', 'AVG', 'DISTINCT'], answer: 'DISTINCT' },
  { subject: 'DBMS', question: 'What is a view in database?', options: ['Physical table', 'Virtual table', 'Index', 'Constraint'], answer: 'Virtual table' },
  { subject: 'DBMS', question: 'Which isolation level prevents dirty reads?', options: ['Read Uncommitted', 'Read Committed', 'Repeatable Read', 'Serializable'], answer: 'Read Committed' },
  { subject: 'DBMS', question: 'What is the purpose of indexing?', options: ['To slow down queries', 'To speed up queries', 'To increase storage', 'None'], answer: 'To speed up queries' },
  { subject: 'DBMS', question: 'Which command is used to remove a table?', options: ['DELETE', 'REMOVE', 'DROP', 'TRUNCATE'], answer: 'DROP' },
  { subject: 'DBMS', question: 'What is a deadlock?', options: ['When transaction waits indefinitely', 'When transaction completes', 'When transaction fails', 'None'], answer: 'When transaction waits indefinitely' },
  { subject: 'DBMS', question: 'Which of the following is not a DDL command?', options: ['CREATE', 'ALTER', 'DROP', 'SELECT'], answer: 'SELECT' },
  { subject: 'DBMS', question: 'What is referential integrity?', options: ['Data consistency between tables', 'Data uniqueness', 'Data redundancy', 'None'], answer: 'Data consistency between tables' },
  { subject: 'DBMS', question: 'Which normal form is also called BCNF?', options: ['2NF', '3NF', '3.5NF', '4NF'], answer: '3.5NF' },
  { subject: 'DBMS', question: 'What is a trigger?', options: ['A special procedure', 'A table', 'An index', 'A constraint'], answer: 'A special procedure' },
  { subject: 'DBMS', question: 'Which of the following is not a NoSQL database?', options: ['MongoDB', 'Cassandra', 'MySQL', 'Redis'], answer: 'MySQL' },

  // Add more subjects similarly...
  // Operating Systems (20 questions)
  { subject: 'Operating Systems', question: 'What is an operating system?', options: ['System software', 'Application software', 'Hardware', 'Firmware'], answer: 'System software' },
  { subject: 'Operating Systems', question: 'Which scheduling algorithm gives minimum average waiting time?', options: ['FCFS', 'SJF', 'Round Robin', 'Priority'], answer: 'SJF' },
  { subject: 'Operating Systems', question: 'What is a process?', options: ['Program in execution', 'Program on disk', 'Program in memory', 'None'], answer: 'Program in execution' },
  { subject: 'Operating Systems', question: 'What is virtual memory?', options: ['Physical memory', 'Secondary storage used as main memory', 'Cache memory', 'Register'], answer: 'Secondary storage used as main memory' },
  { subject: 'Operating Systems', question: 'Which algorithm is used for page replacement?', options: ['FIFO', 'LRU', 'Optimal', 'All of the above'], answer: 'All of the above' },
  { subject: 'Operating Systems', question: 'What is a semaphore?', options: ['Synchronization primitive', 'Data structure', 'Algorithm', 'Hardware'], answer: 'Synchronization primitive' },
  { subject: 'Operating Systems', question: 'What is deadlock?', options: ['Process waiting indefinitely', 'Process completion', 'Process creation', 'None'], answer: 'Process waiting indefinitely' },
  { subject: 'Operating Systems', question: 'Which is not a deadlock prevention method?', options: ['Mutual exclusion', 'Hold and wait', 'No preemption', 'Aging'], answer: 'Aging' },
  { subject: 'Operating Systems', question: 'What is thrashing?', options: ['Excessive paging', 'Process creation', 'Memory allocation', 'None'], answer: 'Excessive paging' },
  { subject: 'Operating Systems', question: 'Which system call is used to create a process?', options: ['fork()', 'exec()', 'wait()', 'exit()'], answer: 'fork()' },
  { subject: 'Operating Systems', question: 'What is context switching?', options: ['Switching between processes', 'Switching between threads', 'Switching between users', 'All'], answer: 'All' },
  { subject: 'Operating Systems', question: 'Which memory allocation technique suffers from external fragmentation?', options: ['Fixed partitioning', 'Dynamic partitioning', 'Paging', 'Segmentation'], answer: 'Dynamic partitioning' },
  { subject: 'Operating Systems', question: 'What is the purpose of MMU?', options: ['Memory allocation', 'Address translation', 'Process scheduling', 'None'], answer: 'Address translation' },
  { subject: 'Operating Systems', question: 'Which scheduling algorithm is preemptive?', options: ['FCFS', 'SJF', 'Round Robin', 'None'], answer: 'Round Robin' },
  { subject: 'Operating Systems', question: 'What is a race condition?', options: ['Multiple processes accessing shared data', 'Process racing', 'Fast execution', 'None'], answer: 'Multiple processes accessing shared data' },
  { subject: 'Operating Systems', question: 'Which is not a file allocation method?', options: ['Contiguous', 'Linked', 'Indexed', 'Hashed'], answer: 'Hashed' },
  { subject: 'Operating Systems', question: 'What is the purpose of TLB?', options: ['Translation Lookaside Buffer', 'Task Load Balancer', 'Thread Local Buffer', 'None'], answer: 'Translation Lookaside Buffer' },
  { subject: 'Operating Systems', question: 'Which is not a process state?', options: ['New', 'Running', 'Waiting', 'Completed'], answer: 'Completed' },
  { subject: 'Operating Systems', question: 'What is spooling?', options: ['Simultaneous Peripheral Operations Online', 'Process scheduling', 'Memory management', 'None'], answer: 'Simultaneous Peripheral Operations Online' },
  { subject: 'Operating Systems', question: 'Which command is used to display running processes?', options: ['ls', 'ps', 'top', 'Both ps and top'], answer: 'Both ps and top' },

  // Computer Networks Questions (25 questions)
  { subject: 'Computer Networks', question: 'What does OSI stand for?', options: ['Open Systems Interconnection', 'Operating Systems Interface', 'Open Source Initiative', 'None'], answer: 'Open Systems Interconnection' },
  { subject: 'Computer Networks', question: 'How many layers are there in the OSI model?', options: ['5', '6', '7', '8'], answer: '7' },
  { subject: 'Computer Networks', question: 'Which layer is responsible for routing?', options: ['Physical', 'Data Link', 'Network', 'Transport'], answer: 'Network' },
  { subject: 'Computer Networks', question: 'What is the default port number for HTTP?', options: ['21', '23', '80', '443'], answer: '80' },
  { subject: 'Computer Networks', question: 'What is the default port number for HTTPS?', options: ['80', '443', '8080', '8443'], answer: '443' },
  { subject: 'Computer Networks', question: 'Which protocol is used for email transmission?', options: ['HTTP', 'FTP', 'SMTP', 'SNMP'], answer: 'SMTP' },
  { subject: 'Computer Networks', question: 'What does TCP stand for?', options: ['Transmission Control Protocol', 'Transfer Control Protocol', 'Transport Control Protocol', 'None'], answer: 'Transmission Control Protocol' },
  { subject: 'Computer Networks', question: 'Which is a connectionless protocol?', options: ['TCP', 'UDP', 'HTTP', 'FTP'], answer: 'UDP' },
  { subject: 'Computer Networks', question: 'What is the maximum length of UTP cable?', options: ['100m', '200m', '500m', '1000m'], answer: '100m' },
  { subject: 'Computer Networks', question: 'Which device operates at the Physical layer?', options: ['Hub', 'Switch', 'Router', 'Gateway'], answer: 'Hub' },
  { subject: 'Computer Networks', question: 'What is the purpose of ARP?', options: ['Address Resolution Protocol', 'Application Request Protocol', 'Automatic Routing Protocol', 'None'], answer: 'Address Resolution Protocol' },
  { subject: 'Computer Networks', question: 'Which topology has the highest reliability?', options: ['Bus', 'Star', 'Ring', 'Mesh'], answer: 'Mesh' },
  { subject: 'Computer Networks', question: 'What is the range of Class A IP addresses?', options: ['1-126', '128-191', '192-223', '224-239'], answer: '1-126' },
  { subject: 'Computer Networks', question: 'Which protocol is used for file transfer?', options: ['HTTP', 'FTP', 'SMTP', 'SNMP'], answer: 'FTP' },
  { subject: 'Computer Networks', question: 'What does DNS stand for?', options: ['Domain Name System', 'Dynamic Name Service', 'Distributed Network Service', 'None'], answer: 'Domain Name System' },
  { subject: 'Computer Networks', question: 'Which layer handles error detection and correction?', options: ['Physical', 'Data Link', 'Network', 'Transport'], answer: 'Data Link' },
  { subject: 'Computer Networks', question: 'What is the purpose of a subnet mask?', options: ['To identify network and host portions', 'To encrypt data', 'To compress data', 'None'], answer: 'To identify network and host portions' },
  { subject: 'Computer Networks', question: 'Which protocol is used for network management?', options: ['HTTP', 'FTP', 'SMTP', 'SNMP'], answer: 'SNMP' },
  { subject: 'Computer Networks', question: 'What is the default subnet mask for Class B?', options: ['255.0.0.0', '255.255.0.0', '255.255.255.0', '255.255.255.255'], answer: '255.255.0.0' },
  { subject: 'Computer Networks', question: 'Which device can connect different network architectures?', options: ['Hub', 'Switch', 'Router', 'Gateway'], answer: 'Gateway' },
  { subject: 'Computer Networks', question: 'What is the maximum data rate of Ethernet?', options: ['10 Mbps', '100 Mbps', '1 Gbps', 'All of the above'], answer: 'All of the above' },
  { subject: 'Computer Networks', question: 'Which protocol is used for remote login?', options: ['HTTP', 'FTP', 'Telnet', 'SMTP'], answer: 'Telnet' },
  { subject: 'Computer Networks', question: 'What does CSMA/CD stand for?', options: ['Carrier Sense Multiple Access/Collision Detection', 'Computer Systems Multiple Access', 'None', 'All'], answer: 'Carrier Sense Multiple Access/Collision Detection' },
  { subject: 'Computer Networks', question: 'Which layer is responsible for data encryption?', options: ['Physical', 'Data Link', 'Network', 'Presentation'], answer: 'Presentation' },
  { subject: 'Computer Networks', question: 'What is the purpose of ICMP?', options: ['Internet Control Message Protocol', 'Internet Connection Management Protocol', 'None', 'All'], answer: 'Internet Control Message Protocol' },

  // Web Development Questions (25 questions)
  { subject: 'Web Development', question: 'What does HTML stand for?', options: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'None'], answer: 'Hyper Text Markup Language' },
  { subject: 'Web Development', question: 'Which HTML tag is used for the largest heading?', options: ['<h1>', '<h6>', '<head>', '<header>'], answer: '<h1>' },
  { subject: 'Web Development', question: 'What does CSS stand for?', options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style Sheets', 'None'], answer: 'Cascading Style Sheets' },
  { subject: 'Web Development', question: 'Which property is used to change the background color in CSS?', options: ['bgcolor', 'background-color', 'color', 'bg-color'], answer: 'background-color' },
  { subject: 'Web Development', question: 'What is the correct JavaScript syntax to change the content of an HTML element?', options: ['document.getElementById("demo").innerHTML = "Hello World!"', 'document.getElement("demo").innerHTML = "Hello World!"', '#demo.innerHTML = "Hello World!"', 'None'], answer: 'document.getElementById("demo").innerHTML = "Hello World!"' },
  { subject: 'Web Development', question: 'Which method is used to add an element to the end of an array in JavaScript?', options: ['push()', 'pop()', 'shift()', 'unshift()'], answer: 'push()' },
  { subject: 'Web Development', question: 'What does DOM stand for?', options: ['Document Object Model', 'Data Object Management', 'Dynamic Object Model', 'None'], answer: 'Document Object Model' },
  { subject: 'Web Development', question: 'Which HTTP method is used to submit form data?', options: ['GET', 'POST', 'PUT', 'DELETE'], answer: 'POST' },
  { subject: 'Web Development', question: 'What is the correct way to create a function in JavaScript?', options: ['function myFunction() {}', 'create myFunction() {}', 'function = myFunction() {}', 'None'], answer: 'function myFunction() {}' },
  { subject: 'Web Development', question: 'Which CSS property is used to make text bold?', options: ['font-weight', 'text-style', 'font-style', 'text-weight'], answer: 'font-weight' },
  { subject: 'Web Development', question: 'What is the purpose of the <head> tag in HTML?', options: ['To contain metadata', 'To contain visible content', 'To create headers', 'None'], answer: 'To contain metadata' },
  { subject: 'Web Development', question: 'Which JavaScript event occurs when the user clicks on an HTML element?', options: ['onchange', 'onclick', 'onmouseclick', 'onmouseover'], answer: 'onclick' },
  { subject: 'Web Development', question: 'What is the correct HTML for creating a hyperlink?', options: ['<a url="http://www.example.com">Example</a>', '<a href="http://www.example.com">Example</a>', '<a>http://www.example.com</a>', 'None'], answer: '<a href="http://www.example.com">Example</a>' },
  { subject: 'Web Development', question: 'Which CSS property is used to change the text color?', options: ['color', 'text-color', 'font-color', 'text-style'], answer: 'color' },
  { subject: 'Web Development', question: 'What does AJAX stand for?', options: ['Asynchronous JavaScript and XML', 'Advanced JavaScript and XML', 'Asynchronous Java and XML', 'None'], answer: 'Asynchronous JavaScript and XML' },
  { subject: 'Web Development', question: 'Which HTML attribute specifies an alternate text for an image?', options: ['alt', 'title', 'src', 'longdesc'], answer: 'alt' },
  { subject: 'Web Development', question: 'What is the correct way to write a JavaScript array?', options: ['var colors = "red", "green", "blue"', 'var colors = (1:"red", 2:"green", 3:"blue")', 'var colors = ["red", "green", "blue"]', 'var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")'], answer: 'var colors = ["red", "green", "blue"]' },
  { subject: 'Web Development', question: 'Which property is used to change the font of an element?', options: ['font-family', 'font-style', 'font-size', 'font'], answer: 'font-family' },
  { subject: 'Web Development', question: 'What is the correct HTML for inserting an image?', options: ['<img alt="MyImage">image.gif</img>', '<img src="image.gif" alt="MyImage">', '<image src="image.gif" alt="MyImage">', '<img href="image.gif" alt="MyImage">'], answer: '<img src="image.gif" alt="MyImage">' },
  { subject: 'Web Development', question: 'Which CSS property controls the text size?', options: ['font-style', 'text-size', 'font-size', 'text-style'], answer: 'font-size' },
  { subject: 'Web Development', question: 'What is the correct way to write a comment in JavaScript?', options: ['<!-- This is a comment -->', '// This is a comment', "' This is a comment", '/* This is a comment */'], answer: '// This is a comment' },
  { subject: 'Web Development', question: 'Which HTML tag is used to define an internal style sheet?', options: ['<style>', '<css>', '<script>', '<link>'], answer: '<style>' },
  { subject: 'Web Development', question: 'What does JSON stand for?', options: ['JavaScript Object Notation', 'Java Standard Object Notation', 'JavaScript Oriented Notation', 'None'], answer: 'JavaScript Object Notation' },
  { subject: 'Web Development', question: 'Which method is used to parse a string to an integer in JavaScript?', options: ['parseInt()', 'parseInteger()', 'int()', 'Integer()'], answer: 'parseInt()' },
  { subject: 'Web Development', question: 'What is the purpose of the DOCTYPE declaration?', options: ['To specify the HTML version', 'To link CSS files', 'To include JavaScript', 'None'], answer: 'To specify the HTML version' },

  // Software Engineering Questions (25 questions)
  { subject: 'Software Engineering', question: 'What does SDLC stand for?', options: ['Software Development Life Cycle', 'System Development Life Cycle', 'Software Design Life Cycle', 'None'], answer: 'Software Development Life Cycle' },
  { subject: 'Software Engineering', question: 'Which model follows a linear sequential approach?', options: ['Waterfall', 'Agile', 'Spiral', 'RAD'], answer: 'Waterfall' },
  { subject: 'Software Engineering', question: 'What is the first phase of SDLC?', options: ['Design', 'Analysis', 'Requirements', 'Testing'], answer: 'Requirements' },
  { subject: 'Software Engineering', question: 'Which testing is performed by developers?', options: ['Unit Testing', 'Integration Testing', 'System Testing', 'Acceptance Testing'], answer: 'Unit Testing' },
  { subject: 'Software Engineering', question: 'What does UML stand for?', options: ['Unified Modeling Language', 'Universal Modeling Language', 'Uniform Modeling Language', 'None'], answer: 'Unified Modeling Language' },
  { subject: 'Software Engineering', question: 'Which diagram shows the interaction between objects?', options: ['Class Diagram', 'Sequence Diagram', 'Use Case Diagram', 'Activity Diagram'], answer: 'Sequence Diagram' },
  { subject: 'Software Engineering', question: 'What is the purpose of version control?', options: ['To track changes', 'To compile code', 'To test software', 'To deploy software'], answer: 'To track changes' },
  { subject: 'Software Engineering', question: 'Which is not a software quality attribute?', options: ['Reliability', 'Usability', 'Complexity', 'Maintainability'], answer: 'Complexity' },
  { subject: 'Software Engineering', question: 'What does DFD stand for?', options: ['Data Flow Diagram', 'Data Function Diagram', 'Dynamic Flow Diagram', 'None'], answer: 'Data Flow Diagram' },
  { subject: 'Software Engineering', question: 'Which model is suitable for small projects?', options: ['Waterfall', 'Prototype', 'Spiral', 'V-Model'], answer: 'Prototype' },
  { subject: 'Software Engineering', question: 'What is the main goal of software engineering?', options: ['To develop quality software', 'To reduce cost', 'To meet deadlines', 'All of the above'], answer: 'All of the above' },
  { subject: 'Software Engineering', question: 'Which testing technique uses the internal structure?', options: ['Black Box', 'White Box', 'Gray Box', 'None'], answer: 'White Box' },
  { subject: 'Software Engineering', question: 'What is refactoring?', options: ['Restructuring code without changing functionality', 'Adding new features', 'Fixing bugs', 'Testing code'], answer: 'Restructuring code without changing functionality' },
  { subject: 'Software Engineering', question: 'Which is not a CASE tool?', options: ['Rational Rose', 'Microsoft Visio', 'Microsoft Word', 'Enterprise Architect'], answer: 'Microsoft Word' },
  { subject: 'Software Engineering', question: 'What does SRS stand for?', options: ['Software Requirements Specification', 'System Requirements Specification', 'Software Requirement Standards', 'None'], answer: 'Software Requirements Specification' },
  { subject: 'Software Engineering', question: 'Which model allows for iterative development?', options: ['Waterfall', 'Agile', 'V-Model', 'Big Bang'], answer: 'Agile' },
  { subject: 'Software Engineering', question: 'What is the purpose of configuration management?', options: ['To manage changes', 'To test software', 'To design software', 'To deploy software'], answer: 'To manage changes' },
  { subject: 'Software Engineering', question: 'Which is not a type of software maintenance?', options: ['Corrective', 'Adaptive', 'Perfective', 'Destructive'], answer: 'Destructive' },
  { subject: 'Software Engineering', question: 'What is the purpose of risk management?', options: ['To identify and mitigate risks', 'To increase project cost', 'To delay project', 'None'], answer: 'To identify and mitigate risks' },
  { subject: 'Software Engineering', question: 'Which diagram shows system behavior?', options: ['Class Diagram', 'Use Case Diagram', 'State Diagram', 'Component Diagram'], answer: 'State Diagram' },
  { subject: 'Software Engineering', question: 'What is the main advantage of modular design?', options: ['Reusability', 'Complexity', 'Cost', 'Time'], answer: 'Reusability' },
  { subject: 'Software Engineering', question: 'Which is not a software process model?', options: ['Waterfall', 'Agile', 'Spiral', 'Linear'], answer: 'Linear' },
  { subject: 'Software Engineering', question: 'What does GUI stand for?', options: ['Graphical User Interface', 'General User Interface', 'Global User Interface', 'None'], answer: 'Graphical User Interface' },
  { subject: 'Software Engineering', question: 'Which testing is performed by end users?', options: ['Unit Testing', 'Integration Testing', 'System Testing', 'Acceptance Testing'], answer: 'Acceptance Testing' },
  { subject: 'Software Engineering', question: 'What is the purpose of software metrics?', options: ['To measure software quality', 'To increase cost', 'To delay project', 'None'], answer: 'To measure software quality' },

  // Machine Learning Questions (25 questions)
  { subject: 'Machine Learning', question: 'What is Machine Learning?', options: ['A subset of AI', 'A programming language', 'A database', 'An operating system'], answer: 'A subset of AI' },
  { subject: 'Machine Learning', question: 'Which type of learning uses labeled data?', options: ['Supervised Learning', 'Unsupervised Learning', 'Reinforcement Learning', 'None'], answer: 'Supervised Learning' },
  { subject: 'Machine Learning', question: 'Which algorithm is used for classification?', options: ['Linear Regression', 'Decision Tree', 'K-Means', 'PCA'], answer: 'Decision Tree' },
  { subject: 'Machine Learning', question: 'What is overfitting?', options: ['Model performs well on training data but poorly on test data', 'Model performs poorly on training data', 'Model performs well on all data', 'None'], answer: 'Model performs well on training data but poorly on test data' },
  { subject: 'Machine Learning', question: 'Which is an unsupervised learning algorithm?', options: ['SVM', 'Decision Tree', 'K-Means', 'Naive Bayes'], answer: 'K-Means' },
  { subject: 'Machine Learning', question: 'What does CNN stand for?', options: ['Convolutional Neural Network', 'Computer Neural Network', 'Cascading Neural Network', 'None'], answer: 'Convolutional Neural Network' },
  { subject: 'Machine Learning', question: 'Which metric is used for regression problems?', options: ['Accuracy', 'Precision', 'Mean Squared Error', 'F1-Score'], answer: 'Mean Squared Error' },
  { subject: 'Machine Learning', question: 'What is the purpose of cross-validation?', options: ['To evaluate model performance', 'To train model', 'To clean data', 'To visualize data'], answer: 'To evaluate model performance' },
  { subject: 'Machine Learning', question: 'Which algorithm is used for dimensionality reduction?', options: ['SVM', 'PCA', 'Decision Tree', 'K-Means'], answer: 'PCA' },
  { subject: 'Machine Learning', question: 'What is gradient descent?', options: ['An optimization algorithm', 'A classification algorithm', 'A clustering algorithm', 'None'], answer: 'An optimization algorithm' },
  { subject: 'Machine Learning', question: 'Which is not a type of neural network?', options: ['CNN', 'RNN', 'ANN', 'SVM'], answer: 'SVM' },
  { subject: 'Machine Learning', question: 'What is the purpose of regularization?', options: ['To prevent overfitting', 'To increase accuracy', 'To reduce training time', 'None'], answer: 'To prevent overfitting' },
  { subject: 'Machine Learning', question: 'Which algorithm is based on Bayes theorem?', options: ['SVM', 'Decision Tree', 'Naive Bayes', 'K-Means'], answer: 'Naive Bayes' },
  { subject: 'Machine Learning', question: 'What is feature selection?', options: ['Selecting relevant features', 'Creating new features', 'Removing outliers', 'Normalizing data'], answer: 'Selecting relevant features' },
  { subject: 'Machine Learning', question: 'Which is an ensemble method?', options: ['SVM', 'Decision Tree', 'Random Forest', 'Linear Regression'], answer: 'Random Forest' },
  { subject: 'Machine Learning', question: 'What does RNN stand for?', options: ['Recurrent Neural Network', 'Recursive Neural Network', 'Random Neural Network', 'None'], answer: 'Recurrent Neural Network' },
  { subject: 'Machine Learning', question: 'Which activation function is commonly used in hidden layers?', options: ['Sigmoid', 'ReLU', 'Tanh', 'All of the above'], answer: 'All of the above' },
  { subject: 'Machine Learning', question: 'What is the purpose of data preprocessing?', options: ['To clean and prepare data', 'To train model', 'To evaluate model', 'To deploy model'], answer: 'To clean and prepare data' },
  { subject: 'Machine Learning', question: 'Which metric is used for classification problems?', options: ['MSE', 'RMSE', 'Accuracy', 'R-squared'], answer: 'Accuracy' },
  { subject: 'Machine Learning', question: 'What is deep learning?', options: ['ML with neural networks having multiple layers', 'ML with decision trees', 'ML with SVM', 'None'], answer: 'ML with neural networks having multiple layers' },
  { subject: 'Machine Learning', question: 'Which algorithm is used for anomaly detection?', options: ['Linear Regression', 'One-Class SVM', 'Decision Tree', 'K-Means'], answer: 'One-Class SVM' },
  { subject: 'Machine Learning', question: 'What is the curse of dimensionality?', options: ['Problems that arise when working with high-dimensional data', 'A type of algorithm', 'A programming error', 'None'], answer: 'Problems that arise when working with high-dimensional data' },
  { subject: 'Machine Learning', question: 'Which is not a hyperparameter?', options: ['Learning rate', 'Number of epochs', 'Weights', 'Batch size'], answer: 'Weights' },
  { subject: 'Machine Learning', question: 'What is transfer learning?', options: ['Using pre-trained models for new tasks', 'Transferring data', 'Moving models', 'None'], answer: 'Using pre-trained models for new tasks' },
  { subject: 'Machine Learning', question: 'Which library is commonly used for ML in Python?', options: ['NumPy', 'Pandas', 'Scikit-learn', 'All of the above'], answer: 'All of the above' },

  // Placement Prep Questions (25 questions)
  { subject: 'Placement Prep', question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], answer: 'O(log n)' },
  { subject: 'Placement Prep', question: 'Which data structure is used in DFS?', options: ['Queue', 'Stack', 'Array', 'Linked List'], answer: 'Stack' },
  { subject: 'Placement Prep', question: 'What is the worst case time complexity of quicksort?', options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'], answer: 'O(n²)' },
  { subject: 'Placement Prep', question: 'Which sorting algorithm is stable?', options: ['Quick Sort', 'Heap Sort', 'Merge Sort', 'Selection Sort'], answer: 'Merge Sort' },
  { subject: 'Placement Prep', question: 'What is the space complexity of merge sort?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(n)' },
  { subject: 'Placement Prep', question: 'Which company was founded by Bill Gates?', options: ['Apple', 'Google', 'Microsoft', 'Facebook'], answer: 'Microsoft' },
  { subject: 'Placement Prep', question: 'What does API stand for?', options: ['Application Programming Interface', 'Advanced Programming Interface', 'Application Process Interface', 'None'], answer: 'Application Programming Interface' },
  { subject: 'Placement Prep', question: 'Which is not a programming paradigm?', options: ['Object-Oriented', 'Functional', 'Procedural', 'Sequential'], answer: 'Sequential' },
  { subject: 'Placement Prep', question: 'What is the maximum number of comparisons in binary search?', options: ['n', 'log n', 'n log n', '1'], answer: 'log n' },
  { subject: 'Placement Prep', question: 'Which data structure allows insertion and deletion at both ends?', options: ['Stack', 'Queue', 'Deque', 'Array'], answer: 'Deque' },
  { subject: 'Placement Prep', question: 'What is the time complexity of inserting at the beginning of a linked list?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(1)' },
  { subject: 'Placement Prep', question: 'Which algorithm is used to find shortest path in unweighted graph?', options: ['DFS', 'BFS', 'Dijkstra', 'Floyd-Warshall'], answer: 'BFS' },
  { subject: 'Placement Prep', question: 'What is the purpose of hashing?', options: ['Fast data retrieval', 'Data compression', 'Data encryption', 'Data sorting'], answer: 'Fast data retrieval' },
  { subject: 'Placement Prep', question: 'Which is not a tree traversal method?', options: ['Inorder', 'Preorder', 'Postorder', 'Crossorder'], answer: 'Crossorder' },
  { subject: 'Placement Prep', question: 'What is the height of a balanced binary tree with n nodes?', options: ['n', 'log n', 'n/2', 'n²'], answer: 'log n' },
  { subject: 'Placement Prep', question: 'Which company developed Java?', options: ['Microsoft', 'Sun Microsystems', 'Google', 'Apple'], answer: 'Sun Microsystems' },
  { subject: 'Placement Prep', question: 'What is the time complexity of heap sort?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(log n)'], answer: 'O(n log n)' },
  { subject: 'Placement Prep', question: 'Which is not a type of database?', options: ['Relational', 'NoSQL', 'Graph', 'Sequential'], answer: 'Sequential' },
  { subject: 'Placement Prep', question: 'What does REST stand for?', options: ['Representational State Transfer', 'Remote State Transfer', 'Relational State Transfer', 'None'], answer: 'Representational State Transfer' },
  { subject: 'Placement Prep', question: 'Which is the most popular version control system?', options: ['SVN', 'Git', 'Mercurial', 'CVS'], answer: 'Git' },
  { subject: 'Placement Prep', question: 'What is the time complexity of accessing an element in an array?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], answer: 'O(1)' },
  { subject: 'Placement Prep', question: 'Which design pattern ensures only one instance of a class?', options: ['Factory', 'Singleton', 'Observer', 'Strategy'], answer: 'Singleton' },
  { subject: 'Placement Prep', question: 'What is the purpose of unit testing?', options: ['Test individual components', 'Test entire system', 'Test user interface', 'Test database'], answer: 'Test individual components' },
  { subject: 'Placement Prep', question: 'Which is not an OOP principle?', options: ['Encapsulation', 'Inheritance', 'Polymorphism', 'Compilation'], answer: 'Compilation' },
  { subject: 'Placement Prep', question: 'What does MVC stand for?', options: ['Model View Controller', 'Multiple View Controller', 'Model Virtual Controller', 'None'], answer: 'Model View Controller' }
];

const seedQuizzes = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Clear existing quiz data
    await Quiz.deleteMany({});
    console.log('Cleared existing quiz data');

    // Insert new quiz questions
    await Quiz.insertMany(quizQuestions);
    console.log(`Inserted ${quizQuestions.length} quiz questions`);

    console.log('Quiz seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding quizzes:', error);
    process.exit(1);
  }
};

seedQuizzes(); 